defaults:
  - data: aeslc

output_dir: './workdir/'
generation_configs_path: ${get_home_path:0}/ue_abssum/configs/generation  # have `:0` since we don't care about the arg
hydra:
  run:
    dir: ${output_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}_${seed}_${to_string:${data.dataset_name}}_${to_string:${model.name}}
  sweep:
    dir: ${output_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}_${seed}_${to_string:${data.dataset_name}}_${to_string:${model.name}}
    subdir: ${hydra.job.num}

cache_dir:
offline_mode: False

data: ???

seed: 42
model_seeds: [42, 23419, 4837, 705525, 12345]

model:
  name: bart-base
  path:
  generation_max_length:
  num_return_sequences: 4
  batch_size: 50
  type: abs-sum

ue_methods:
  names:
  emb_model_path:
  ensemble:
      de_model_paths:
      batch_size: 32
  kwargs:
    softmax_t: 1

metrics_to_use:
