defaults:
  - ood_base_config
  - data: sanity_check
  - ood_data: sanity_check

# Config used to check that it's ok to launch experiments
# Things to look out for:
# 1. Nothing crashes
# 2. There are PRR and RCC plots for BARTscore, ROUGE*, BLEU, SUMMAC, accuracy
# 3. There is ROC-AUC plot
# 4. SACREBLEUVAR has one score < random

model_seeds: [42]

generation_configs_path: ${get_home_path:0}/ue_abssum/configs/generation_testing
ood:
  corrupt: false
