defaults:
  - data: aeslc
  - ood_data: xsum

output_dir: './workdir/'
generation_configs_path: ${get_home_path:0}/ue_abssum/configs/generation  # have `:0` since we don't care about the arg
hydra:
  run:
    dir: ${output_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}_${seed}_${data.dataset_name}_${ood_data.dataset_name}
  sweep:
    dir: ${output_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}_${seed}_${data.dataset_name}_${ood_data.dataset_name}
    subdir: ${hydra.job.num}

seed: 42
cache_dir:
offline_mode: False

data: ???
ood_data: ???

model_seeds: [42, 23419, 4837, 705525, 12345]

model:
  name: bart-base
  path:
  generation_max_length:
  num_return_sequences: 4
  batch_size: 50

ue_methods:
  names:
  emb_model_path:
  ensemble:
      de_model_paths:
      batch_size: 32
  kwargs:
    softmax_t: 1

ood:
  tokenizer: facebook/bart-base
  corrupt: False
  shuffle: False

metrics_to_use:

with_random: true
