defaults:
  - data: testing

output_dir: './workdir/'
generation_configs_path: ${get_home_path:0}/ue_abssum/configs/generation_testing  # have `:0` since we don't care about the arg
hydra:
  run:
    dir: ${output_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}_${seed}_${to_string:${model.name}}
  sweep:
    dir: ${output_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}_${seed}_${to_string:${model.name}}
    subdir: ${hydra.job.num}

seed: 42
cache_dir:
offline_mode: False
mc_iterations: 2

data: ???

model:
  name: stub
  path: hf-internal-testing/tiny-random-bart
  generation_max_length:
  num_return_sequences: 4
  batch_size: 50
  type: abs-sum

ue_methods:
  names:
  emb_model_path: hf-internal-testing/tiny-bert
  de_model_paths: ["hf-internal-testing/tiny-random-bart"]
  ensemble:
    de_model_paths: ["hf-internal-testing/tiny-random-bart"]
    batch_size: 32
  kwargs:
    softmax_t: 1

model_seeds: [42]

metrics_to_use:  # TODO add support for testing all methods (current args use heavy models)
  - rouge
  - bleu
