defaults:
  - ood_base_config_t5_42
  - data: wdsq
  - ood_data: wdsq_ru

ue_methods:
  type: cuda_ensemble

ood:
  corrupt: false

model:
  device: 0

cache_dir: '~/sq_en_ru_cuda_ensemble'
experiment_name: 'sq_en_ru_cuda_ensemble_42'
