defaults:
  - ood_base_config_t5_705525
  - data: wdsq
  - ood_data: wdsq

ue_methods:
  type: cuda_ensemble

ood:
  corrupt: true

model:
  device: 0

cache_dir: '~/sq_sq_cuda_ensemble'
experiment_name: 'sq_sq_cuda_ensemble_705525'
