defaults:
  - ood_base_config_t5
  - data: wdsq
  - ood_data: mintaka

ue_methods:
  type: single

ood:
  corrupt: false

model:
  device: 0

cache_dir: '~/sq_mintaka_single'
experiment_name: 'sq_mintaka_single'
