defaults:
  - ood_base_config_t5
  - data: wdsq
  - ood_data: wdsq

ue_methods:
  type: embeddings

ood:
  corrupt: true

model:
  device: 0

cache_dir: '~/sq_sq_embeddings'
experiment_name: 'sq_sq_embeddings'
