defaults:
  - ood_base_config_t5
  - data: rubq_en
  - ood_data: rubq_en

ue_methods:
  type: single

ood:
  corrupt: true

model:
  device: 0

cache_dir: '~/rubq_rubq_single'
experiment_name: 'rubq_rubq_single'
