defaults:
  - ood_base_config_t5
  - data: wdsq
  - ood_data: wdsq_ru

ue_methods:
  type: single

ood:
  corrupt: false

model:
  device: 0

cache_dir: '~/sq_en_ru_single'
experiment_name: 'sq_en_ru_single'
