defaults:
  - ood_base_config_t5
  - data: rubq_en
  - ood_data: mintaka

ue_methods:
  type: cuda_ensemble

ood:
  corrupt: false

model:
  device: 0

cache_dir: '~/rubq_mintaka_cuda_ensemble'
experiment_name: 'rubq_mintaka_cuda_ensemble'
