defaults:
  - ood_base_config_t5
  - data: rubq_en
  - ood_data: mintaka

ue_methods:
  type: embeddings

ood:
  corrupt: false

model:
  device: 0

cache_dir: '~/rubq_mintaka_embeddings'
experiment_name: 'rubq_mintaka_embeddings'
