defaults:
  - sp_base_config_t5
  - data: rubq_en

ue_methods:
  type: single

prefix_tree: False
model:
  device: 0
  name: google/t5-large-ssm-nq
  path: google/t5-large-ssm-nq

cache_dir: '~/sp_rubq_en_single'
experiment_name: 'sp_rubq_en_single'
