defaults:
  - sp_base_config_t5
  - data: mintaka

ue_methods:
  type: ensemble

prefix_tree: True
model:
  device: 0
  name: google/t5-small-ssm-nq
  path: google/t5-small-ssm-nq

cache_dir: '~/prefix_sp_mintaka_ensemble'
experiment_name: 'prefix_sp_mintaka_ensemble'
