defaults:
  - sp_base_config_t5
  - data: rubq_en

ue_methods:
  type: embeddings

prefix_tree: True
model:
  device: 0
  name: google/t5-small-ssm-nq
  path: google/t5-small-ssm-nq

cache_dir: '~/prefix_sp_rubq_en_embeddings'
experiment_name: 'prefix_sp_rubq_en_embeddings'
