defaults:
  - sp_base_config_t5
  - data: rubq_en

ue_methods:
  type: single

inference_seed: 42
dropout_rates: [0.5, 0.3, 0.1, 0.07, 0.05, 0.04, 0.03, 0.02, 0.01, 0.0]

prefix_tree: True
model:
  device: 0
  name: google/t5-xl-ssm-nq
  path: google/t5-xl-ssm-nq

cache_dir: '~/prefix_sp_rubq_en_single'
experiment_name: 'prefix_sp_rubq_en_single'
