defaults:
  - sp_base_config_t5
  - data: rubq_en

ue_methods:
  type: single

prefix_tree: True
model:
  device: 0
  name: google/t5-large-ssm-nq
  path: '/trinity/home/r.vashurin/t5_large_ft/checkpoint-3654'

cache_dir: '~/prefix_sp_rubq_en_single'
experiment_name: 'prefix_sp_rubq_en_single'
