defaults:
  - sp_base_config_t5
  - data: rubq_ru

ue_methods:
  type: cuda_ensemble

prefix_tree: True
model:
  device: 0
  name: google/t5-xl-ssm-nq
  path: google/t5-xl-ssm-nq

cache_dir: '~/prefix_sp_rubq_ru_cuda_ensemble'
experiment_name: 'prefix_sp_rubq_ru_cuda_ensemble'
