defaults:
  - sp_base_config_t5
  - data: wdsq

ue_methods:
  type: single

model:
  device: 0
  name: google/t5-xl-ssm-nq
  path: google/t5-xl-ssm-nq

cache_dir: '~/prefix_sp_sq_en_single'
experiment_name: 'prefix_sp_sq_en_single'
