defaults:
  - sp_base_config_t5
  - data: wdsq

ue_methods:
  type: embeddings

prefix_tree: True
model:
  device: 0

cache_dir: '~/prefix_sp_sq_en_embeddings'
experiment_name: 'prefix_sp_sq_en_embeddings'
