defaults:
  - sp_base_config_t5
  - data: wdsq

ue_methods:
  type: mc_ensemble

prefix_tree: True
model:
  device: 0
  name: google/t5-xl-ssm-nq
  path: google/t5-xl-ssm-nq

cache_dir: '~/prefix_sp_sq_en_mc_ensemble'
experiment_name: 'prefix_sp_sq_en_mc_ensemble'
