defaults:
  - sp_base_config_t5
  - data: wdsq_ru

ue_methods:
  type: single

prefix_tree: True
model:
  device: 0
  name: google/t5-small-ssm-nq
  path: google/t5-small-ssm-nq

cache_dir: '~/prefix_sp_sq_ru_single'
experiment_name: 'prefix_sp_sq_ru_single'
