defaults:
  - sp_base_config_t5
  - data: wdsq

ue_methods:
  type: single

prefix_tree: True
corrupt_data: True

model:
  device: 0
  name: google/t5-small-ssm-nq
  path: google/t5-small-ssm-nq

cache_dir: '~/prefix_sp_rubq_en_single'
experiment_name: 'prefix_sp_rubq_en_single'
