defaults:
  - sp_base_config_t5
  - data: wdsq

ue_methods:
  type: cuda_ensemble
  ensemble:
    ensembling_mode: pe
    dropout_rate: 0.5

prefix_tree: True
model:
  device: 0
  name: google/t5-large-ssm-nq
  path: '/trinity/home/r.vashurin/t5_large_wdsq_44/checkpoint-18064'

cache_dir: '~/prefix_sp_rubq_en_cuda_ensemble_pe'
experiment_name: 'prefix_sp_rubq_en_cuda_ensemble_pe'
