defaults:
  - sp_base_config_t5
  - data: wdsq

model:
  device: 0
  name: google/t5-large-ssm-nq
  path: google/t5-large-ssm-nq

cache_dir: '~/train_t5_rubq'
experiment_name: 'train_t5_rubq'

training_seed: 705528
checkpoint_dir: '/trinity/home/r.vashurin/t5_large_wdsq_705528'
