output_dir: './workdir/aggregated_results'
hydra:
  run:
    dir: ${output_dir}
  sweep:
    dir: ${output_dir}
    subdir: ${hydra.job.num}

seed: 42
offline_mode: False
ats_metrics_names: ['Top 1 Acc', 'Top all Acc', 'MRR']
model_seeds: [42, 23419, 4837, 705525, 12345]
ue_approaches: [single]
ood: False

model:
  name: google/t5-large-ssm-nq

ue_results:
  rubq_en:
    output_dir: ${output_dir}/rubq_en_sp_prefix_large
    result_paths:
      single: 'workdir/2023-02-08/42_wikidata_rubq_single_rubq_en_single/'
