output_dir: './workdir/aggregated_results'
hydra:
  run:
    dir: ${output_dir}
  sweep:
    dir: ${output_dir}
    subdir: ${hydra.job.num}

seed: 42
offline_mode: False
ats_metrics_names: ['Accuracy']
model_seeds: [42, 23419, 4837, 705525, 12345]
ood: True 

ue_results:
  sq_en_ru:
    output_dir: ${output_dir}/sq_en_ru
    result_paths:
      single: 'workdir/2023-02-14/42_wikidata_simplequestions_wikidata_simplequestions_ru_single_sq_en_ru_single/'
      mc_ensemble: 'workdir/2023-02-14/42_wikidata_simplequestions_wikidata_simplequestions_ru_mc_ensemble_sq_en_ru_mc_ensemble/'
      cuda_ensemble: 'workdir/2023-02-14/42_wikidata_simplequestions_wikidata_simplequestions_ru_cuda_ensemble_sq_en_ru_cuda_ensemble/'
      embeddings: 'workdir/2023-02-14/42_wikidata_simplequestions_wikidata_simplequestions_ru_embeddings_sq_en_ru_embeddings/'
  sq_mintaka:
    output_dir: ${output_dir}/sq_mintaka
    result_paths:
      single: 'workdir/2023-02-02/42_wikidata_simplequestions_AmazonScience/mintaka_single_sq_mintaka_single/'
      mc_ensemble: 'workdir/2023-02-02/42_wikidata_simplequestions_AmazonScience/mintaka_mc_ensemble_sq_mintaka_mc_ensemble/'
      cuda_ensemble: 'workdir/2023-02-01/42_wikidata_simplequestions_AmazonScience/mintaka_cuda_ensemble_sq_mintaka_cuda_ensemble/'
      embeddings: 'workdir/2023-02-01/42_wikidata_simplequestions_AmazonScience/mintaka_embeddings_sq_mintaka_embeddings/'

